set(CONFIG_SOC "Daric NTO A")
set(CONFIG_SOC_SERIES "daric")
set(CONFIG_ARCH "arm")
set(CONFIG_ARM "y")
set(CONFIG_CPU_CORTEX_M7 "y")

set(CONFIG_SYS_CLOCK_TICKS_PER_SEC "1000")
set(CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC "250000000")

set(CONFIG_BOARD_ACTIVECARD_NTO_DVT3 "y")

#LCD
set(CONFIG_LCD_COMMON "y")
set(CONFIG_LCD_ED028TC1_SPI "y")

#lcd spi config
set(CONFIG_LCD_SPI_ID "1")
set(CONFIG_LCD_SPI_BAUDRATE "20000000")
set(CONFIG_LCD_ULPS_MODE "1")

# define a macro to set LCD pin configuration
macro(set_lcd_pin name port pin is_required)
    set(CONFIG_LCD_${name}_PORT ${port})
    set(CONFIG_LCD_${name}_PIN ${pin})
    set(CONFIG_LCD_${name}_IS_REQUIRED ${is_required})
endmacro()

# use macro to set LCD pin configuration
set_lcd_pin(VCIEN   GPIOD   GPIO_PIN_11     false)
set_lcd_pin(RST     GPIOF   GPIO_PIN_3     false)
set_lcd_pin(BUSY    GPIOC   GPIO_PIN_13     false)

# AW9523B GPIO Expander and LED Driver

# RTC
set(CONFIG_RTC_INS5T8900 "y")
set(CONFIG_RTC_INS5T8900_INT_PORT "GPIOB")
set(CONFIG_RTC_INS5T8900_INT_PIN "GPIO_PIN_2")
set(CONFIG_RTC_I2C_ID "DARIC_I2C1_ID")
set(CONFIG_RTC_I2C_SPEED "100")

# Set alarm to power off from PD mode
set(CONFIG_PD_RTC_ALARM_TO_POWEROFF "y")

# Show PD Mode Window
set(CONFIG_SHOW_PD_WINDOW "y")

# PMIC
set(CONFIG_PMIC "y")
set(CONFIG_PMIC_TG28 "y")
set(CONFIG_PMIC_TG28_INT_PORT "GPIOF")
set(CONFIG_PMIC_TG28_INT_PIN "GPIO_PIN_0")
set(CONFIG_PMIC_I2C_ID "DARIC_I2C1_ID")
set(CONFIG_PMIC_I2C_SPEED "100")
set(CONFIG_PMIC_I2C_ADDR "0x34")

set(CONFIG_BATT_CHG "y")
set(CONFIG_BATT_ETA4662 "y")
set(CONFIG_BATT_ETA4662_INT_PORT "GPIOE")
set(CONFIG_BATT_ETA4662_INT_PIN "GPIO_PIN_1")
set(CONFIG_BATT_I2C_ID "DARIC_I2C1_ID")
set(CONFIG_BATT_I2C_SPEED "100")
set(CONFIG_BATT_I2C_ADDR "0x07")

set(CONFIG_PMU_POWER_CTRL "y")
set(CONFIG_TOUCH_POWR               "PMU_PWR_BLDO2")
set(CONFIG_USB_POWER_3V1            "PMU_PWR_ALDO3")
set(CONFIG_CLOCK_POWER              "PMU_PWR_DCDC2")
#set(CONFIG_BLUETOOTH_POWER          "PMU_PWR_DLDO3")   BLE power controled by GPIO PB8
#set(CONFIG_SD_POWER                 "PMU_PWR_DLDO3")   No SD card
#set(CONFIG_FINGERPRINT_POWER_ADD    "PMU_PWR_DLDO4")   Fingerprint power controled by GPIO PB3
set(CONFIG_USB_POWER_0V9            "PMU_PWR_CPUSLDO")

# RGB LED
set(CONFIG_RGB_LED "y")
set(CONFIG_RGB_LED_CHIP "1")        # 1： AW2023; 2: AW91XXX
set(CONFIG_RGB_LED_I2C_ID "DARIC_I2C2_ID")
set(CONFIG_RGB_LED_I2C_SPEED "100")

# Touch
set(CONFIG_TOUCH "y")
set(CONFIG_TOUCH_IIC_ID "DARIC_I2C3_ID")
set(CONFIG_TOUCH_IIC_SPEED "400")
set(CONFIG_TOUCH_RST_PORT "GPIOB")
set(CONFIG_TOUCH_RST_PIN "GPIO_PIN_0")
set(CONFIG_TOUCH_INT_PORT "GPIOB")
set(CONFIG_TOUCH_INT_PIN "GPIO_PIN_1")
set(CONFIG_TOUCH_X_RESOLUTION "480")
set(CONFIG_TOUCH_Y_RESOLUTION "600")
set(CONFIG_TOUCH_SWAP_XY "0")
set(CONFIG_TOUCH_REVERSE_X "1")
set(CONFIG_TOUCH_REVERSE_Y "1")

# FINGERPRINT
set(CONFIG_FINGERPRINT "y")
set(CONFIG_FP_SPI_ID   "3")
set(CONFIG_FP_SPI_PORT "GPIOE")
set(CONFIG_FP_SPI_CS   "GPIO_PIN_9")
set(CONFIG_FP_INT_PORT "GPIOC")
set(CONFIG_FP_INT_PIN  "GPIO_PIN_10")
set(CONFIG_FP_PW_CTRL  "y")
set(CONFIG_FP_PW_PORT  "GPIOB")
set(CONFIG_FP_PW_PIN   "GPIO_PIN_3")

# NFC
set(CONFIG_NFC "y")
set(CONFIG_NFC_DARIC_ACTIVECARD "y")
set(CONFIG_NFC_I2C_ID "DARIC_I2C0_ID")
set(CONFIG_NFC_VEN_PORT "GPIOB")
set(CONFIG_NFC_VEN_PIN "GPIO_PIN_6")
set(CONFIG_NFC_DWL_PORT "GPIOB")
set(CONFIG_NFC_DWL_PIN "GPIO_PIN_5")
set(CONFIG_NFC_IRQ_PORT "GPIOE")
set(CONFIG_NFC_IRQ_PIN "GPIO_PIN_14")
set(CONFIG_NFC_VDDIO_PORT "GPIOD")
set(CONFIG_NFC_VDDIO_PIN "GPIO_PIN_15")

# BT
set(CONFIG_BT "y")
set(CONFIG_BLUETOOTH_HAL_UART_ID "UART2_ID")
set(CONFIG_BLUETOOTH_HAL_UART_BAUDRATE "2000000")
set(CONFIG_BT_POWER_PORT "GPIOB")
set(CONFIG_BT_POWER_PIN "GPIO_PIN_4")

#USB
set(CONFIG_USB_DETEC "y")

# G-sensor

# Vibrator
set(CONFIG_VIBRATOR "y")
set(CONFIG_VIBRATOR_I2C_ID "DARIC_I2C2_ID")
set(CONFIG_VIBRATOR_I2C_SPEED "100")
set(CONFIG_VIBRATOR_I2C_ADDR "0x5A")
set(CONFIG_AW8623X_DRIVER "y")
set(CONFIG_AW_RST_GPIO_PORT "GPIOB")
set(CONFIG_AW_RST_Pin GPIO_PIN_9)
set(CONFIG_AW_IRQ_GPIO_PORT "GPIOB")
set(CONFIG_AW_IRQ_Pin GPIO_PIN_7)

# Flash
set(CONFIG_FLASH_SPI_ID   "0")
set(CONFIG_FLASH_SPI_BAUDRATE "20000000")
set(CONFIG_FLASH_SPI_PORT "GPIOD")
set(CONFIG_FLASH_SPI_CS   "GPIO_PIN_5")

