/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.4.0.0                                               */
/*  Date (dd.mm.yyyy):  1. 6.2026   Time (hh:mm): 10:24                        */
/*******************************************************************************/


#ifndef _DARIC_GUI_SPECIFICATIONS_H_
#define _DARIC_GUI_SPECIFICATIONS_H_

#include "gx_api.h"

/* Determine if C++ compiler is being used, if so use standard C.              */
#ifdef __cplusplus
extern   "C" {
#endif

/* Define widget ids                                                           */

#define ID_NUMBER_KEYBOARD_WIN 1
#define ID_MESSAGE_DIALOG_WIN 2
#define ID_CANCEL_DIALOG_BTN 3
#define ID_OK_DIALOG_BTN 4
#define ID_PROMPT_DIALOG_TITLE 5
#define ID_PROMPT_DIALOG_MESSAGE 6
#define ID_FM_LCD_REFRESH_MM_WIN 7
#define ID_GC16_REFRESH 8
#define ID_A2_REFRESH 9
#define ID_DU2_REFRESH 10
#define ID_FM_LCD_GRAY_MM_TEST_WIN 11
#define ID_FACTORY_MODE_STORAGE_WIN 12
#define ID_FACTORY_MODE_VERSION_INFO_WIN 13
#define ID_VERSION_INFO_BUILD_NUMBER 14
#define ID_VERSION_INFO_SERIAL_NUMBER 15
#define ID_VERSION_INFO_BT_FW_VERSION 16
#define ID_VERSION_INFO_BOOTLOADER_VERSION 17
#define ID_VERSION_INFO_HARDWARE_VERSION 18
#define ID_VERSION_INFO_FACTORY_SN 19
#define ID_FACTORY_MODE_FIRST_WIN 20
#define ID_FACTORY_MODE_TOUCH_SCREEN 21
#define ID_FACTORY_MODE_LED 22
#define ID_FACTORY_MODE_VIBRATOR 23
#define ID_FACTORY_MODE_CHARGER 24
#define ID_FACTORY_MODE_BLUETOOTH 25
#define ID_FACTORY_MODE_LCD 26
#define ID_FACTORY_MODE_KEY 27
#define ID_FACTORY_MODE_FINGERPRINT 28
#define ID_FACTORY_MODE_RTC 29
#define ID_FACTORY_MODE_NFC 30
#define ID_FACTORY_MODE_STORAGE 31
#define ID_FACTORY_MODE_NFC_WIN 32
#define ID_FACTORY_MODE_NFC_BTN 33
#define ID_FACTORY_MODE_NFC_STATUS 34
#define ID_FACTORY_MODE_BLUETOOTH_WIN 35
#define ID_FACTORY_MODE_BLUETOOTH_ADDRESS 36
#define ID_FACTORY_MODE_BLUETOOTH_NAME 37
#define ID_FACTORY_MODE_BLUETOOTH_BTN 38
#define ID_FACTORY_MODE_BLUETOOTH_STATUS 39
#define ID_FACTORY_MODE_RTC_WIN 40
#define ID_FACTORY_MODE_RTC_SET_BTN 41
#define ID_FACTORY_MODE_RTC_GET_BTN 42
#define ID_FACTORY_MODE_RTC_SET_ERROR_PROMPT 43
#define ID_FACTORY_MODE_CHARGER_WIN 44
#define ID_FACTORY_MODE_CHARGER_STATUS 45
#define ID_FACTORY_MODE_CHARGER_LEVEL 46
#define ID_FACTORY_MODE_FINGERPRINT_WIN 47
#define ID_FACTORY_MODE_FINGERPRINT_CALIBRATE_BTN 48
#define ID_FACTORY_MODE_FINGERPRINT_START_BTN 49
#define ID_FACTORY_MODE_FINGERPRINT_DETECTED_ICON 50
#define ID_FACTORY_MODE_VIBRATOR_WIN 51
#define ID_FACTORY_MODE_VIBRATOR_BTN 52
#define ID_FACTORY_MODE_LINEAR_VIBRATOR_TEST 53
#define ID_FACTORY_MODE_KEY_WIN 54
#define ID_FACTORY_MODE_KEY_STATUS 55
#define ID_FACTORY_MODE_LED_WIN 56
#define ID_FACTORY_MODE_LED_BTN 57
#define ID_FACTORY_MODE_LCD_WIN 58
#define ID_FACTORY_MODE_TOUCHSCREEN_WIN 59
#define ID_FACTORY_MODE_TOUCHSCREEN_CENTER_BTN 60
#define ID_FACTORY_MODE_TOUCHSCREEN_LEFT_BOTTOM_BTN 61
#define ID_FACTORY_MODE_TOUCHSCREEN_LEFT_TOP_BTN 62
#define ID_FACTORY_MODE_TOUCHSCREEN_RIGHT_BOTTOM_BTN 63
#define ID_FACTORY_MODE_TOUCHSCREEN_RIGHT_TOP_BTN 64
#define ID_FACTORY_MODE_TOUCHSCREEN_LEFT_CENTER_BTN 65
#define ID_FACTORY_MODE_TOUCHSCREEN_RIGHT_CENTER_BTN 66
#define ID_FACTORY_MODE_SECOND_WIN 67
#define ID_FACTORY_MODE_VERSION_INFO 68
#define ID_SIMPLE_NAV_BACK_BTN 69
#define ID_OOBE_NAV_BACK_BTN 70
#define ID_FACTORY_MODE_WIN_TITLE 71
#define ID_FACTORY_MODE_WIN_DESCRIPTION 72
#define ID_FACTORY_MODE_COMMON_BACK_BTN 73
#define ID_FACTORY_MODE_COMMON_FAILED_BTN 74
#define ID_FACTORY_MODE_COMMON_NEXT_BTN 75
#define ID_FACTORY_MODE_COMMON_PASS_BTN 76
#define ID_HOME_SINGLE_BACK_WINDOW 77
#define ID_NAV_BACK 78
#define ID_OOBE_SINGLE_NEXT_WIN 79
#define ID_OOBE_SINGLE_NAV_NEXT 80
#define ID_OOBE_NAV_NEXT_BTN 81
#define ID_OOBE_SINGLE_BACK_WIN 82
#define ID_OOBE_single_NAV_BACK 83
#define ID_OOBE_COMMON_WINDOW 84
#define ID_OOBE_NAV_BACK 85
#define ID_OOBE_NAV_NEXT 86
#define ID_HOME_WINDOW 87
#define ID_NAV_HOME 88
#define ID_OOBE_NAV_HOME_BTN 89
#define ID_NAV_SETTINGS 90
#define ID_OOBE_NAV_SETTINGS_BTN 91


/* Define animation ids                                                        */

#define GX_NEXT_ANIMATION_ID 1


/* Define user event ids                                                       */

#define GX_NEXT_USER_EVENT_ID GX_FIRST_USER_EVENT


/* Declare properties structures for each utilized widget type                 */

typedef struct GX_STUDIO_WIDGET_STRUCT
{
   GX_CHAR *widget_name;
   USHORT  widget_type;
   USHORT  widget_id;
   #if defined(GX_WIDGET_USER_DATA)
   INT   user_data;
   #endif
   ULONG style;
   ULONG status;
   ULONG control_block_size;
   GX_RESOURCE_ID normal_fill_color_id;
   GX_RESOURCE_ID selected_fill_color_id;
   GX_RESOURCE_ID disabled_fill_color_id;
   UINT (*create_function) (GX_CONST struct GX_STUDIO_WIDGET_STRUCT *, GX_WIDGET *, GX_WIDGET *);
   void (*draw_function) (GX_WIDGET *);
   UINT (*event_function) (GX_WIDGET *, GX_EVENT *);
   GX_RECTANGLE size;
   GX_CONST struct GX_STUDIO_WIDGET_STRUCT *next_widget;
   GX_CONST struct GX_STUDIO_WIDGET_STRUCT *child_widget;
   ULONG control_block_offset;
   GX_CONST void *properties;
} GX_STUDIO_WIDGET;

typedef struct
{
    GX_CONST GX_STUDIO_WIDGET *widget_information;
    GX_WIDGET        *widget;
} GX_STUDIO_WIDGET_ENTRY;

typedef struct
{
    GX_RESOURCE_ID string_id; 
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
} GX_TEXT_BUTTON_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id; 
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
    GX_RESOURCE_ID unchecked_pixelmap_id;
    GX_RESOURCE_ID checked_pixelmap_id;
    GX_RESOURCE_ID unchecked_disabled_pixelmap_id;
    GX_RESOURCE_ID checked_disabled_pixelmap_id;
} GX_CHECKBOX_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID pixelmap_id;
} GX_ICON_BUTTON_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID normal_pixelmap_id;
    GX_RESOURCE_ID selected_pixelmap_id;
} GX_ICON_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id;
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
} GX_PROMPT_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id;
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
    VOID (*format_func)(GX_NUMERIC_PROMPT *, INT);
    INT            numeric_prompt_value;
} GX_NUMERIC_PROMPT_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID wallpaper_id;
} GX_WINDOW_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id;
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
    GX_RESOURCE_ID readonly_fill_color_id;
    GX_RESOURCE_ID readonly_text_color_id;
    GX_CHAR *buffer;
    UINT buffer_size;
} GX_SINGLE_LINE_TEXT_INPUT_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id;
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
    GX_UBYTE       whitespace;
    GX_BYTE        line_space;
} GX_ML_TEXT_VIEW_PROPERTIES;

typedef struct
{
   GX_CONST GX_STUDIO_WIDGET *base_info;
   UINT (*base_create_function) (GX_CONST struct GX_STUDIO_WIDGET_STRUCT *, GX_WIDGET *, GX_WIDGET *);
   GX_RECTANGLE size;
} GX_TEMPLATE_PROPERTIES;


/* Declare top-level control blocks                                            */

typedef struct NUMBER_KEYBOARD_WIN_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
} NUMBER_KEYBOARD_WIN_CONTROL_BLOCK;

typedef struct MESSAGE_DIALOG_WIN_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
    GX_TEXT_BUTTON message_dialog_win_cancel_dialog_btn;
    GX_TEXT_BUTTON message_dialog_win_ok_dialog_btn;
    GX_PROMPT message_dialog_win_prompt_dialog_title;
    GX_MULTI_LINE_TEXT_VIEW message_dialog_win_prompt_dialog_message;
} MESSAGE_DIALOG_WIN_CONTROL_BLOCK;

typedef struct FM_LCD_REFRESH_MM_WIN_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
    GX_PROMPT fm_lcd_refresh_mm_win_gc16_refresh;
    GX_PROMPT fm_lcd_refresh_mm_win_a2_refresh;
    GX_PROMPT fm_lcd_refresh_mm_win_du2_refresh;
} FM_LCD_REFRESH_MM_WIN_CONTROL_BLOCK;

typedef struct FM_LCD_GRAY_MM_TEST_WIN_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
    GX_ICON fm_lcd_gray_mm_test_win_gray_0_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_1_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_2_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_3_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_4_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_5_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_6_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_7_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_8_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_9_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_a_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_b_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_c_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_d_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_e_icon;
    GX_ICON fm_lcd_gray_mm_test_win_gray_f_icon;
} FM_LCD_GRAY_MM_TEST_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_LCD_BLACK_WIN_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
} FACTORY_MODE_LCD_BLACK_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_LCD_WHITE_WIN_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
} FACTORY_MODE_LCD_WHITE_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_LCD_GRAY_WIN_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
} FACTORY_MODE_LCD_GRAY_WIN_CONTROL_BLOCK;

typedef struct SIMPLE_SINGLE_BACK_TEMPLATE_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
    GX_PROMPT simple_single_back_template_simple_nav_back_btn;
    GX_ICON_BUTTON simple_single_back_template_oobe_nav_back_btn_2;
} SIMPLE_SINGLE_BACK_TEMPLATE_CONTROL_BLOCK;

typedef struct FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
    GX_PROMPT factory_mode_common_window_factory_mode_win_title;
    GX_MULTI_LINE_TEXT_VIEW factory_mode_common_window_factory_mode_win_description;
    GX_PROMPT factory_mode_common_window_factory_mode_common_back_btn;
    GX_PROMPT factory_mode_common_window_factory_mode_common_failed_btn;
    GX_PROMPT factory_mode_common_window_factory_mode_common_next_btn;
    GX_PROMPT factory_mode_common_window_factory_mode_common_pass_btn;
} FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK;

typedef struct OOBE_SINGLE_NEXT_WIN_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
    GX_PROMPT oobe_single_next_win_oobe_single_nav_next;
    GX_ICON_BUTTON oobe_single_next_win_oobe_nav_next_btn;
} OOBE_SINGLE_NEXT_WIN_CONTROL_BLOCK;

typedef struct OOBE_SINGLE_BACK_WIN_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
    GX_PROMPT oobe_single_back_win_oobe_single_nav_back;
    GX_ICON_BUTTON oobe_single_back_win_oobe_nav_back_btn;
} OOBE_SINGLE_BACK_WIN_CONTROL_BLOCK;

typedef struct OOBE_COMMON_WINDOW_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
    GX_PROMPT oobe_common_window_oobe_nav_back;
    GX_ICON_BUTTON oobe_common_window_oobe_nav_back_btn;
    GX_PROMPT oobe_common_window_oobe_nav_next;
    GX_ICON_BUTTON oobe_common_window_oobe_nav_next_btn;
} OOBE_COMMON_WINDOW_CONTROL_BLOCK;

typedef struct ROOT_WINDOW_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
} ROOT_WINDOW_CONTROL_BLOCK;

typedef struct FACTORY_MODE_STORAGE_WIN_CONTROL_BLOCK_STRUCT
{
    FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK base;
    GX_WINDOW factory_mode_storage_win_reram_status;
    GX_PROMPT factory_mode_storage_win_reram_status_title;
    GX_PROMPT factory_mode_storage_win_reram_status_summary;
    GX_WINDOW factory_mode_storage_win_nand_flash_status;
    GX_PROMPT factory_mode_storage_win_nand_flash_status_title;
    GX_PROMPT factory_mode_storage_win_nand_flash_status_summary;
} FACTORY_MODE_STORAGE_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_VERSION_INFO_WIN_CONTROL_BLOCK_STRUCT
{
    OOBE_SINGLE_BACK_WIN_CONTROL_BLOCK base;
    GX_WINDOW factory_mode_version_info_win_version_info_build_number;
    GX_PROMPT factory_mode_version_info_win_version_info_build_number_title;
    GX_PROMPT factory_mode_version_info_win_version_info_build_number_summary;
    GX_WINDOW factory_mode_version_info_win_version_info_serial_number;
    GX_PROMPT factory_mode_version_info_win_version_info_serial_number_title;
    GX_PROMPT factory_mode_version_info_win_version_info_serial_number_summary;
    GX_WINDOW factory_mode_version_info_win_version_info_bluetooth_fw_version;
    GX_PROMPT factory_mode_version_info_win_version_info_bt_fw_version_title;
    GX_PROMPT factory_mode_version_info_win_version_info_bt_firmware_version_summary;
    GX_WINDOW factory_mode_version_info_win_version_info_bootloader_version;
    GX_PROMPT factory_mode_version_info_win_version_info_bootloader_version_title;
    GX_PROMPT factory_mode_version_info_win_version_info_bootloader_version_summary;
    GX_PROMPT factory_mode_version_info_win_version_info_title;
    GX_WINDOW factory_mode_version_info_win_version_info_hardware_version;
    GX_PROMPT factory_mode_version_info_win_version_info_hardware_version_title;
    GX_PROMPT factory_mode_version_info_win_version_info_hardware_version_summary;
    GX_WINDOW factory_mode_version_info_win_version_info_factory_sn;
    GX_PROMPT factory_mode_version_info_win_version_info_factory_sn_title;
    GX_PROMPT factory_mode_version_info_win_version_info_factory_sn_summary;
} FACTORY_MODE_VERSION_INFO_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_FIRST_WIN_CONTROL_BLOCK_STRUCT
{
    OOBE_COMMON_WINDOW_CONTROL_BLOCK base;
    GX_PROMPT factory_mode_first_win_factory_mode_touch_screen;
    GX_ICON factory_mode_first_win_factory_mode_touch_screen_icon;
    GX_TEXT_BUTTON factory_mode_first_win_factory_mode_touch_screen_title;
    GX_PROMPT factory_mode_first_win_factory_mode_touch_screen_test_status;
    GX_PROMPT factory_mode_first_win_factory_mode_title;
    GX_PROMPT factory_mode_first_win_factory_mode_led;
    GX_ICON factory_mode_first_win_factory_mode_led_icon;
    GX_TEXT_BUTTON factory_mode_first_win_factory_mode_led_title;
    GX_PROMPT factory_mode_first_win_factory_mode_led_test_status;
    GX_PROMPT factory_mode_first_win_factory_mode_vibrator;
    GX_ICON factory_mode_first_win_factory_mode_vibrator_icon;
    GX_TEXT_BUTTON factory_mode_first_win_factory_mode_vibrator_title;
    GX_PROMPT factory_mode_first_win_factory_mode_vibrator_test_status;
    GX_PROMPT factory_mode_first_win_factory_mode_charger;
    GX_ICON factory_mode_first_win_factory_mode_charger_icon;
    GX_TEXT_BUTTON factory_mode_first_win_factory_mode_charger_title;
    GX_PROMPT factory_mode_first_win_factory_mode_charger_test_status;
    GX_PROMPT factory_mode_first_win_factory_mode_bluetooth;
    GX_ICON factory_mode_first_win_factory_mode_bluetooth_icon;
    GX_TEXT_BUTTON factory_mode_first_win_factory_mode_bluetooth_title;
    GX_PROMPT factory_mode_first_win_factory_mode_bluetooth_test_status;
    GX_PROMPT factory_mode_first_win_factory_mode_lcd;
    GX_ICON factory_mode_first_win_factory_mode_lcd_icon;
    GX_TEXT_BUTTON factory_mode_first_win_factory_mode_lcd_title;
    GX_PROMPT factory_mode_first_win_factory_mode_lcd_test_status;
    GX_PROMPT factory_mode_first_win_factory_mode_key;
    GX_ICON factory_mode_first_win_factory_mode_key_icon;
    GX_TEXT_BUTTON factory_mode_first_win_factory_mode_key_title;
    GX_PROMPT factory_mode_first_win_factory_mode_key_test_status;
    GX_PROMPT factory_mode_first_win_factory_mode_fingerprint;
    GX_ICON factory_mode_first_win_factory_mode_fingerprint_icon;
    GX_TEXT_BUTTON factory_mode_first_win_factory_mode_touch_fingerprint_title;
    GX_PROMPT factory_mode_first_win_factory_mode_fingerprint_test_status;
    GX_PROMPT factory_mode_first_win_factory_mode_rtc;
    GX_ICON factory_mode_first_win_factory_mode_rtc_icon;
    GX_TEXT_BUTTON factory_mode_first_win_factory_mode_rtc_title;
    GX_PROMPT factory_mode_first_win_factory_mode_rtc_test_status;
    GX_PROMPT factory_mode_first_win_factory_mode_nfc;
    GX_ICON factory_mode_first_win_factory_mode_nfc_icon;
    GX_TEXT_BUTTON factory_mode_first_win_factory_mode_nfc_title;
    GX_PROMPT factory_mode_first_win_factory_mode_nfc_test_status;
    GX_PROMPT factory_mode_first_win_factory_mode_storage;
    GX_ICON factory_mode_first_win_factory_mode_storage_icon;
    GX_TEXT_BUTTON factory_mode_first_win_factory_mode_storage_title;
    GX_PROMPT factory_mode_first_win_factory_mode_storage_test_status;
    GX_WINDOW factory_mode_first_win_window;
} FACTORY_MODE_FIRST_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_NFC_WIN_CONTROL_BLOCK_STRUCT
{
    FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK base;
    GX_TEXT_BUTTON factory_mode_nfc_win_factory_mode_nfc_btn;
    GX_PROMPT factory_mode_nfc_win_factory_mode_nfc_status;
} FACTORY_MODE_NFC_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_BLUETOOTH_WIN_CONTROL_BLOCK_STRUCT
{
    FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK base;
    GX_PROMPT factory_mode_bluetooth_win_factory_mode_bluetooth_address;
    GX_PROMPT factory_mode_bluetooth_win_factory_mode_bluetooth_name;
    GX_TEXT_BUTTON factory_mode_bluetooth_win_factory_mode_bluetooth_btn;
    GX_PROMPT factory_mode_bluetooth_win_factory_mode_bluetooth_status;
} FACTORY_MODE_BLUETOOTH_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_RTC_WIN_CONTROL_BLOCK_STRUCT
{
    FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK base;
    GX_SINGLE_LINE_TEXT_INPUT factory_mode_rtc_win_factory_mode_rtc_input_year;
    GX_SINGLE_LINE_TEXT_INPUT factory_mode_rtc_win_factory_mode_rtc_input_month;
    GX_SINGLE_LINE_TEXT_INPUT factory_mode_rtc_win_factory_mode_rtc_input_day;
    GX_PROMPT factory_mode_rtc_win_factory_mode_rct_year;
    GX_PROMPT factory_mode_rtc_win_factory_mode_rct_month;
    GX_PROMPT factory_mode_rtc_win_factory_mode_rtc_day;
    GX_SINGLE_LINE_TEXT_INPUT factory_mode_rtc_win_factory_mode_rtc_input_hour;
    GX_SINGLE_LINE_TEXT_INPUT factory_mode_rtc_win_factory_mode_rtc_input_minute;
    GX_PROMPT factory_mode_rtc_win_factory_mode_rtc_time_minute_separation;
    GX_PROMPT factory_mode_rtc_win_factory_mode_rtc_hour;
    GX_PROMPT factory_mode_rtc_win_factory_mode_rtc_minute;
    GX_TEXT_BUTTON factory_mode_rtc_win_factory_mode_rtc_set_btn;
    GX_TEXT_BUTTON factory_mode_rtc_win_factory_mode_rtc_get_btn;
    GX_PROMPT factory_mode_rtc_win_factory_mode_rtc_date;
    GX_PROMPT factory_mode_rtc_win_factory_mode_rtc_time;
    GX_PROMPT factory_mode_rtc_win_factory_mode_rtc_set_error_prompt;
    GX_SINGLE_LINE_TEXT_INPUT factory_mode_rtc_win_factory_mode_rtc_input_second;
    GX_PROMPT factory_mode_rtc_win_factory_mode_rtc_second;
    GX_PROMPT factory_mode_rtc_win_factory_mode_rtc_time_second_separation;
} FACTORY_MODE_RTC_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_CHARGER_WIN_CONTROL_BLOCK_STRUCT
{
    FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK base;
    GX_PROMPT factory_mode_charger_win_factory_mode_charger_status;
    GX_PROMPT factory_mode_charger_win_factory_mode_charger_level;
} FACTORY_MODE_CHARGER_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_FINGERPRINT_WIN_CONTROL_BLOCK_STRUCT
{
    FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK base;
    GX_TEXT_BUTTON factory_mode_fingerprint_win_factory_mode_fingerprint_calibrate_btn;
    GX_TEXT_BUTTON factory_mode_fingerprint_win_factory_mode_fingerprint_start_btn;
    GX_ICON factory_mode_fingerprint_win_factory_mode_fingerprint_detected_icon;
} FACTORY_MODE_FINGERPRINT_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_VIBRATOR_WIN_CONTROL_BLOCK_STRUCT
{
    FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK base;
    GX_TEXT_BUTTON factory_mode_vibrator_win_factory_mode_vibrator_btn;
    GX_CHECKBOX factory_mode_vibrator_win_factory_mode_linear_vibrator_test;
    GX_PROMPT factory_mode_vibrator_win_factory_mode_vibrator_test_left;
    GX_NUMERIC_PROMPT factory_mode_vibrator_win_factory_mode_vibrator_test_left_counts;
    GX_PROMPT factory_mode_vibrator_win_factory_mode_vibrator_test_left_title;
} FACTORY_MODE_VIBRATOR_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_KEY_WIN_CONTROL_BLOCK_STRUCT
{
    FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK base;
    GX_PROMPT factory_mode_key_win_factory_mode_key_status;
} FACTORY_MODE_KEY_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_LED_WIN_CONTROL_BLOCK_STRUCT
{
    FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK base;
    GX_TEXT_BUTTON factory_mode_led_win_factory_mode_led_btn;
} FACTORY_MODE_LED_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_LCD_WIN_CONTROL_BLOCK_STRUCT
{
    FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK base;
    GX_PROMPT factory_mode_lcd_win_factory_mode_lcd_empyt_view;
} FACTORY_MODE_LCD_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_TOUCHSCREEN_WIN_CONTROL_BLOCK_STRUCT
{
    FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK base;
    GX_TEXT_BUTTON factory_mode_touchscreen_win_factory_mode_touchscreen_center_btn;
    GX_TEXT_BUTTON factory_mode_touchscreen_win_factory_mode_touchscreen_left_bottom_btn;
    GX_TEXT_BUTTON factory_mode_touchscreen_win_factory_mode_touchscreen_left_top_btn;
    GX_TEXT_BUTTON factory_mode_touchscreen_win_factory_mode_touchscreen_right_bottom_btn;
    GX_TEXT_BUTTON factory_mode_touchscreen_win_factory_mode_touchscreen_right_top_btn;
    GX_TEXT_BUTTON factory_mode_touchscreen_win_factory_mode_touchscreen_left_center_btn;
    GX_TEXT_BUTTON factory_mode_touchscreen_win_factory_mode_touchscreen_right_center_btn;
} FACTORY_MODE_TOUCHSCREEN_WIN_CONTROL_BLOCK;

typedef struct FACTORY_MODE_SECOND_WIN_CONTROL_BLOCK_STRUCT
{
    OOBE_SINGLE_BACK_WIN_CONTROL_BLOCK base;
    GX_PROMPT factory_mode_second_win_factory_mode_title;
    GX_PROMPT factory_mode_second_win_factory_mode_version_info;
    GX_TEXT_BUTTON factory_mode_second_win_factory_mode_version_info_title;
    GX_ICON factory_mode_second_win_factory_mode_version_info_icon;
} FACTORY_MODE_SECOND_WIN_CONTROL_BLOCK;

typedef struct HOME_SINGLE_BACK_WINDOW_CONTROL_BLOCK_STRUCT
{
    ROOT_WINDOW_CONTROL_BLOCK base;
    GX_PROMPT home_single_back_window_nav_back_btn;
    GX_ICON_BUTTON home_single_back_window_oobe_nav_back_btn;
} HOME_SINGLE_BACK_WINDOW_CONTROL_BLOCK;

typedef struct HOME_WINDOW_CONTROL_BLOCK_STRUCT
{
    ROOT_WINDOW_CONTROL_BLOCK base;
    GX_PROMPT home_window_nav_back_btn;
    GX_ICON_BUTTON home_window_oobe_nav_back_btn;
    GX_PROMPT home_window_nav_home_btn;
    GX_ICON_BUTTON home_window_oobe_nav_home_btn;
    GX_PROMPT home_window_nav_settings_btn;
    GX_ICON_BUTTON home_window_oobe_nav_settings_btn;
} HOME_WINDOW_CONTROL_BLOCK;


/* extern statically defined control blocks                                    */

#ifndef GUIX_STUDIO_GENERATED_FILE
extern NUMBER_KEYBOARD_WIN_CONTROL_BLOCK number_keyboard_win;
extern MESSAGE_DIALOG_WIN_CONTROL_BLOCK message_dialog_win;
extern FM_LCD_REFRESH_MM_WIN_CONTROL_BLOCK fm_lcd_refresh_mm_win;
extern FM_LCD_GRAY_MM_TEST_WIN_CONTROL_BLOCK fm_lcd_gray_mm_test_win;
extern FACTORY_MODE_STORAGE_WIN_CONTROL_BLOCK factory_mode_storage_win;
extern FACTORY_MODE_VERSION_INFO_WIN_CONTROL_BLOCK factory_mode_version_info_win;
extern FACTORY_MODE_FIRST_WIN_CONTROL_BLOCK factory_mode_first_win;
extern FACTORY_MODE_NFC_WIN_CONTROL_BLOCK factory_mode_nfc_win;
extern FACTORY_MODE_BLUETOOTH_WIN_CONTROL_BLOCK factory_mode_bluetooth_win;
extern FACTORY_MODE_RTC_WIN_CONTROL_BLOCK factory_mode_rtc_win;
extern FACTORY_MODE_CHARGER_WIN_CONTROL_BLOCK factory_mode_charger_win;
extern FACTORY_MODE_LCD_BLACK_WIN_CONTROL_BLOCK factory_mode_lcd_black_win;
extern FACTORY_MODE_LCD_WHITE_WIN_CONTROL_BLOCK factory_mode_lcd_white_win;
extern FACTORY_MODE_LCD_GRAY_WIN_CONTROL_BLOCK factory_mode_lcd_gray_win;
extern FACTORY_MODE_FINGERPRINT_WIN_CONTROL_BLOCK factory_mode_fingerprint_win;
extern FACTORY_MODE_VIBRATOR_WIN_CONTROL_BLOCK factory_mode_vibrator_win;
extern FACTORY_MODE_KEY_WIN_CONTROL_BLOCK factory_mode_key_win;
extern FACTORY_MODE_LED_WIN_CONTROL_BLOCK factory_mode_led_win;
extern FACTORY_MODE_LCD_WIN_CONTROL_BLOCK factory_mode_lcd_win;
extern FACTORY_MODE_TOUCHSCREEN_WIN_CONTROL_BLOCK factory_mode_touchscreen_win;
extern FACTORY_MODE_SECOND_WIN_CONTROL_BLOCK factory_mode_second_win;
extern SIMPLE_SINGLE_BACK_TEMPLATE_CONTROL_BLOCK simple_single_back_template;
extern FACTORY_MODE_COMMON_WINDOW_CONTROL_BLOCK factory_mode_common_window;
extern HOME_SINGLE_BACK_WINDOW_CONTROL_BLOCK home_single_back_window;
extern OOBE_SINGLE_NEXT_WIN_CONTROL_BLOCK oobe_single_next_win;
extern OOBE_SINGLE_BACK_WIN_CONTROL_BLOCK oobe_single_back_win;
extern OOBE_COMMON_WINDOW_CONTROL_BLOCK oobe_common_window;
extern HOME_WINDOW_CONTROL_BLOCK home_window;
extern ROOT_WINDOW_CONTROL_BLOCK root_window;
#endif

/* Declare event process functions, draw functions, and callback functions     */

UINT message_dialog_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT fm_lcd_mm_test_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT factory_mode_test_item_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT factory_mode_version_info_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT factory_mode_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT factory_mode_txt_input_event_process(GX_SINGLE_LINE_TEXT_INPUT *widget, GX_EVENT *event_ptr);
VOID status_bar_draw(GX_WINDOW *widget);

/* Declare the GX_STUDIO_DISPLAY_INFO structure                                */


typedef struct GX_STUDIO_DISPLAY_INFO_STRUCT 
{
    GX_CONST GX_CHAR *name;
    GX_CONST GX_CHAR *canvas_name;
    GX_CONST GX_THEME **theme_table;
    GX_CONST GX_STRING **language_table;
    USHORT   theme_table_size;
    USHORT   language_table_size;
    UINT     string_table_size;
    UINT     x_resolution;
    UINT     y_resolution;
    GX_DISPLAY *display;
    GX_CANVAS  *canvas;
    GX_WINDOW_ROOT *root_window;
    GX_COLOR   *canvas_memory;
    ULONG      canvas_memory_size;
    USHORT     rotation_angle;
} GX_STUDIO_DISPLAY_INFO;


/* Declare Studio-generated functions for creating top-level widgets           */

UINT gx_studio_text_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_checkbox_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_icon_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_icon_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_prompt_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_numeric_prompt_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_window_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_text_input_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_multi_line_text_view_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_template_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
GX_WIDGET *gx_studio_widget_create(GX_BYTE *storage, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent);
UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget);
UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *), GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root);

/* Determine if a C++ compiler is being used.  If so, complete the standard
  C conditional started above.                                                 */
#ifdef __cplusplus
}
#endif

#endif                                       /* sentry                         */
