/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.4.0.0                                               */
/*  Date (dd.mm.yyyy):  1. 6.2026   Time (hh:mm): 10:24                        */
/*******************************************************************************/


#ifndef _DARIC_GUI_MAIN_DISPLAY_RESOURCES_H_
#define _DARIC_GUI_MAIN_DISPLAY_RESOURCES_H_

#include "gx_api.h"

#if !defined(GX_UTF8_SUPPORT)
#error "The symbol GX_UTF8_SUPPORT must be defined to support the Studio project settings".
#endif

/* Display and theme definitions                                               */

#define MAIN_DISPLAY 0
#define MAIN_DISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_4BIT_GRAY
#define MAIN_DISPLAY_X_RESOLUTION 480
#define MAIN_DISPLAY_Y_RESOLUTION 600
#define MAIN_DISPLAY_THEME_1 0
#define MAIN_DISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define MAIN_DISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_WHITE 29
#define GX_COLOR_ID_GREEN 30
#define GX_COLOR_ID_BASE_BG_WHITE_COLOR 31
#define GX_COLOR_ID_BLACK 32
#define GX_COLOR_ID_DARK_GRAY 33
#define GX_COLOR_ID_GRAY 34
#define GX_COLOR_ID_LIGHT_GREY_BG 35
#define GX_COLOR_ID_TEXT_COLOR_GRAY_1 36
#define GX_COLOR_ID_BASE_BG_BLACK_COLOR 37
#define GX_COLOR_ID_TEXT_COLOR_GRAY_2 38
#define GX_COLOR_ID_TEXT_COLOR_GRAY_11 39
#define GX_COLOR_ID_TEXT_COLOR_GRAY_12 40
#define GX_COLOR_ID_TEXT_COLOR_GRAY_13 41
#define GX_COLOR_ID_GRAY_0 42
#define GX_COLOR_ID_GRAY_1 43
#define GX_COLOR_ID_GRAY_2 44
#define GX_COLOR_ID_GRAY_3 45
#define GX_COLOR_ID_GRAY_4 46
#define GX_COLOR_ID_GRAY_5 47
#define GX_COLOR_ID_GRAY_6 48
#define GX_COLOR_ID_GRAY_7 49
#define GX_COLOR_ID_GRAY_8 50
#define GX_COLOR_ID_GRAY_9 51
#define GX_COLOR_ID_GRAY_A 52
#define GX_COLOR_ID_GRAY_B 53
#define GX_COLOR_ID_GRAY_C 54
#define GX_COLOR_ID_GRAY_D 55
#define GX_COLOR_ID_GRAY_E 56
#define GX_COLOR_ID_GRAY_F 57
#define MAIN_DISPLAY_COLOR_TABLE_SIZE 58

/* Font ID definitions                                                         */

#define GX_FONT_ID_FONT_REGULAR_12_1BPP 4
#define GX_FONT_ID_FONT_BOLD_22_1BPP 5
#define GX_FONT_ID_FONT_BOLD_32_1BPP 6
#define GX_FONT_ID_FONT_REGULAR_18_1BPP 7
#define GX_FONT_ID_FONT_BOLD_38_1BPP 8
#define GX_FONT_ID_FONT_REGULAR_36_1BPP 9
#define GX_FONT_ID_FONT_REGULAR_22_1BPP 10
#define GX_FONT_ID_FONT_MEDIUM_40_4BPP 11
#define GX_FONT_ID_FONT_REGULAR_26_1BPP 12
#define GX_FONT_ID_FONT_BOLD_24_1BPP 13
#define GX_FONT_ID_FONT_REGULAR_20_1BPP 14
#define GX_FONT_ID_PASS_FAIL_FONT 15
#define MAIN_DISPLAY_FONT_TABLE_SIZE 16

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_FINGER_PRINT 5
#define GX_PIXELMAP_ID_NAV_BACK 6
#define GX_PIXELMAP_ID_NAV_HOME 7
#define GX_PIXELMAP_ID_NAV_NEXT 8
#define MAIN_DISPLAY_PIXELMAP_TABLE_SIZE 9

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_25 1
#define GX_STRING_ID_STRING_48 2
#define GX_STRING_ID_STRING_49 3
#define GX_STRING_ID_STRING_52 4
#define GX_STRING_ID_STRING_194 5
#define GX_STRING_ID_STRING_201 6
#define GX_STRING_ID_STRING_243 7
#define GX_STRING_ID_STRING_249 8
#define GX_STRING_ID_STRING_272 9
#define GX_STRING_ID_STRING_324 10
#define GX_STRING_ID_STRING_325 11
#define GX_STRING_ID_STRING_326 12
#define GX_STRING_ID_STRING_335 13
#define GX_STRING_ID_STRING_336 14
#define GX_STRING_ID_STRING_374 15
#define GX_STRING_ID_STRING_381 16
#define GX_STRING_ID_STRING_382 17
#define GX_STRING_ID_STRING_383 18
#define GX_STRING_ID_STRING_384 19
#define GX_STRING_ID_STRING_385 20
#define GX_STRING_ID_STRING_386 21
#define GX_STRING_ID_STRING_387 22
#define GX_STRING_ID_STRING_388 23
#define GX_STRING_ID_STRING_389 24
#define GX_STRING_ID_STRING_390 25
#define GX_STRING_ID_STRING_398 26
#define GX_STRING_ID_STRING_401 27
#define GX_STRING_ID_STRING_404 28
#define GX_STRING_ID_STRING_406 29
#define GX_STRING_ID_STRING_407 30
#define GX_STRING_ID_STRING_408 31
#define GX_STRING_ID_STRING_421 32
#define GX_STRING_ID_STRING_422 33
#define GX_STRING_ID_STRING_423 34
#define GX_STRING_ID_STRING_425 35
#define GX_STRING_ID_STRING_432 36
#define GX_STRING_ID_STRING_436 37
#define GX_STRING_ID_STRING_437 38
#define GX_STRING_ID_STRING_438 39
#define GX_STRING_ID_STRING_439 40
#define GX_STRING_ID_STRING_440 41
#define GX_STRING_ID_STRING_442 42
#define GX_STRING_ID_STRING_444 43
#define GX_STRING_ID_STRING_458 44
#define GX_STRING_ID_STRING_459 45
#define GX_STRING_ID_STRING_460 46
#define GX_STRING_ID_STRING_462 47
#define GX_STRING_ID_STRING_463 48
#define GX_STRING_ID_STRING_464 49
#define GX_STRING_ID_STRING_466 50
#define GX_STRING_ID_STRING_467 51
#define GX_STRING_ID_STRING_468 52
#define GX_STRING_ID_STRING_514 53
#define GX_STRING_ID_STRING_515 54
#define GX_STRING_ID_STRING_516 55
#define GX_STRING_ID_STRING_518 56
#define GX_STRING_ID_STRING_519 57
#define GX_STRING_ID_STRING_521 58
#define GX_STRING_ID_STRING_520 59
#define GX_STRING_ID_STRING_522 60
#define GX_STRING_ID_STRING_524 61
#define GX_STRING_ID_STRING_553 62
#define GX_STRING_ID_STRING_575 63
#define GX_STRING_ID_STRING_576 64
#define GX_STRING_ID_STRING_4 65
#define GX_STRING_ID_STRING_12 66
#define GX_STRING_ID_STRING_27 67
#define GX_STRING_ID_STRING_70 68
#define GX_STRING_ID_STRING_71 69
#define GX_STRING_ID_STRING_75 70
#define GX_STRING_ID_STRING_78 71
#define GX_STRING_ID_STRING_84 72
#define GX_STRING_ID_STRING_94 73
#define GX_STRING_ID_STRING_98 74
#define GX_STRING_ID_STRING_99 75
#define GX_STRING_ID_STRING_100 76
#define GX_STRING_ID_STRING_101 77
#define GX_STRING_ID_STRING_103 78
#define GX_STRING_ID_STRING_104 79
#define GX_STRING_ID_STRING_106 80
#define GX_STRING_ID_STRING_105 81
#define GX_STRING_ID_STRING_116 82
#define GX_STRING_ID_STRING_117 83
#define GX_STRING_ID_STRING_118 84
#define GX_STRING_ID_STRING_119 85
#define GX_STRING_ID_STRING_120 86
#define GX_STRING_ID_STRING_122 87
#define GX_STRING_ID_STRING_124 88
#define GX_STRING_ID_STRING_126 89
#define GX_STRING_ID_STRING_123 90
#define GX_STRING_ID_STRING_125 91
#define GX_STRING_ID_STRING_127 92
#define GX_STRING_ID_STRING_128 93
#define GX_STRING_ID_STRING_129 94
#define GX_STRING_ID_STRING_130 95
#define GX_STRING_ID_STRING_131 96
#define GX_STRING_ID_STRING_132 97
#define GX_STRING_ID_STRING_133 98
#define GX_STRING_ID_STRING_134 99
#define GX_STRING_ID_STRING_135 100
#define GX_STRING_ID_STRING_136 101
#define GX_STRING_ID_STRING_137 102
#define GX_STRING_ID_STRING_138 103
#define GX_STRING_ID_STRING_195 104
#define GX_STRING_ID_STRING_196 105
#define GX_STRING_ID_STRING_1 106
#define GX_STRING_ID_STRING_2 107
#define MAIN_DISPLAY_STRING_TABLE_SIZE 108

#endif                                       /* sentry                         */
