
set(CONFIG_BOARD "Daric-EVB-NTO")
set(CONFIG_SOC_DARIC_NTO_A "y")
set(CONFIG_SUPPORT_800MFREQ "y")
set(CONFIG_NEWLIB_LIBC "y")
set(CONFIG_EXECUTION_MODE "RERAM_MODE")

# HAL driver modules
set(HAL_UART_MODULE_ENABLED "y")
set(HAL_UDMA_MODULE_ENABLED "y")
set(HAL_NVIC_MODULE_ENABLED "y")
set(HAL_IFRAMMGR_MODULE_ENABLED "y")
set(HAL_PINMAP_MODULE_ENABLED "y")
set(HAL_GPIO_MODULE_ENABLED "y")
set(HAL_ATIMER_MODULE_ENABLED "y")
set(HAL_TICK_ATIMER_ENABLED "y")
set(HAL_I2C_MODULE_ENABLED "y")
